@echo off
REM =========================================================================
REM  BOT Exchange Rate Processor — Single-Command Setup (Windows)
REM =========================================================================
REM  Usage:  Double-click setup.bat  OR  run in Command Prompt
REM  This script performs a full environment setup from scratch:
REM    1. Checks for Python 3 and Git
REM    2. Creates a virtual environment
REM    3. Installs all dependencies
REM    4. Prompts for API credentials
REM    5. Opens the project folder
REM =========================================================================

title BOT Exchange Rate Processor - Setup
color 0F
cls

echo.
echo  ╔══════════════════════════════════════════════════════════╗
echo  ║                                                        ║
echo  ║   BOT Exchange Rate Processor — Environment Setup      ║
echo  ║                                                        ║
echo  ╚══════════════════════════════════════════════════════════╝
echo.

REM ═══════════════════════════════════════════════════════════════════════
REM  PRIORITY 1: Strict Dependency Checks
REM ═══════════════════════════════════════════════════════════════════════
echo  [1/4] Checking system dependencies...
echo.

SET FAIL=0

REM ── Python check ───────────────────────────────────────────────────────
python --version >nul 2>&1
IF %ERRORLEVEL% EQU 0 (
    FOR /F "tokens=*" %%i IN ('python --version 2^>^&1') DO echo    ✓ Python found: %%i
) ELSE (
    echo.
    echo  ╔══════════════════════════════════════════════════════╗
    echo  ║  ✗ FATAL: Python 3 is NOT installed.               ║
    echo  ║                                                    ║
    echo  ║  Download from:                                    ║
    echo  ║  https://www.python.org/downloads/                 ║
    echo  ║                                                    ║
    echo  ║  IMPORTANT: Check "Add Python to PATH" during      ║
    echo  ║  installation, then restart this script.           ║
    echo  ╚══════════════════════════════════════════════════════╝
    echo.
    SET FAIL=1
)

REM ── Git check ──────────────────────────────────────────────────────────
git --version >nul 2>&1
IF %ERRORLEVEL% EQU 0 (
    FOR /F "tokens=*" %%i IN ('git --version 2^>^&1') DO echo    ✓ Git found: %%i
) ELSE (
    echo.
    echo  ╔══════════════════════════════════════════════════════╗
    echo  ║  ✗ FATAL: Git is NOT installed.                    ║
    echo  ║                                                    ║
    echo  ║  Download from:                                    ║
    echo  ║  https://git-scm.com/downloads/win                 ║
    echo  ╚══════════════════════════════════════════════════════╝
    echo.
    SET FAIL=1
)

IF %FAIL% EQU 1 (
    echo.
    echo  Setup cannot continue. Install the missing tools above and re-run.
    echo.
    pause
    exit /b 1
)

echo.

REM ═══════════════════════════════════════════════════════════════════════
REM  PRIORITY 2: Virtual Environment & Dependencies
REM ═══════════════════════════════════════════════════════════════════════
echo  [2/4] Setting up Python virtual environment...

IF NOT EXIST "venv" (
    python -m venv venv
    echo    ✓ Virtual environment created.
) ELSE (
    echo    → Virtual environment already exists, reusing.
)

echo    → Installing dependencies (this may take a minute)...
venv\Scripts\pip.exe install -q --upgrade pip 2>nul
venv\Scripts\pip.exe install -q -r requirements.txt 2>nul
echo    ✓ All dependencies installed.
echo.

REM ═══════════════════════════════════════════════════════════════════════
REM  PRIORITY 3: API Credential Setup
REM ═══════════════════════════════════════════════════════════════════════
echo  [3/4] Configuring API credentials...

IF EXIST ".env" (
    echo    → .env file already exists. Skipping credential setup.
    echo      (Delete .env and re-run setup to reconfigure)
    GOTO SKIP_ENV
)

echo.
echo    You need two API keys from the Bank of Thailand.
echo    Register at: https://apiportal.bot.or.th/
echo.

SET /P TOKEN_EXG="   Paste your Exchange Rate API key (BOT_TOKEN_EXG): "
SET /P TOKEN_HOL="   Paste your Holiday API key      (BOT_TOKEN_HOL): "

IF "%TOKEN_EXG%"=="" SET TOKEN_EXG=paste_your_exchange_rate_api_key_here
IF "%TOKEN_HOL%"=="" SET TOKEN_HOL=paste_your_holiday_api_key_here

(
    echo # BOT Exchange Rate Processor — API Credentials
    echo # Generated by setup.bat on %DATE% %TIME%
    echo BOT_TOKEN_EXG=%TOKEN_EXG%
    echo BOT_TOKEN_HOL=%TOKEN_HOL%
) > .env

echo    ✓ .env file created successfully.

:SKIP_ENV
echo.

REM ═══════════════════════════════════════════════════════════════════════
REM  Folder Reveal & Success
REM ═══════════════════════════════════════════════════════════════════════
echo  [4/4] Finalizing...
echo.
echo  ╔══════════════════════════════════════════════════════════╗
echo  ║                                                        ║
echo  ║   ✓  Setup Complete!                                   ║
echo  ║                                                        ║
echo  ║   You can now run the application:                     ║
echo  ║                                                        ║
echo  ║     venv\Scripts\python.exe main.py                    ║
echo  ║                                                        ║
echo  ╚══════════════════════════════════════════════════════════╝
echo.

REM Open the project folder in Windows Explorer
explorer .

pause
